### ISSUE TITLE
Nested Values

### ISSUE THREAD

**Issue by marshauf** [mockersf/serde_dynamodb#1]
Hello,

while I was implementing the missing functionality I noticed that you serialize nested values flat into a HashMap with keys like "parent-child". DynamoDB supports nested values. The child values of a struct can be stored in an AttributeValue { M: HashMap::new()  } .
Any reason why you don't do that?

**Comment by mockersf** [comment]
Hey !
Yes... laziness, and not knowing that much about DynamoDB...
I implemented the minimum that I needed to make my case work, and didn't have time to continue since

**Comment by marshauf** [comment]
I continued your work and implemented the missing number types, vectors, nested structs, char and Option. Would you be interested in a pull request?

**Comment by mockersf** [comment]
I would love it !

**Comment by mockersf** [comment]
I published the crate with your changes, I think it now covers enough cases to be useful
