### ISSUE TITLE
Cut a new release?

### ISSUE THREAD

**Issue by Mcat12** [mockersf/serde_dynamodb#139]
`master` has the update to rusoto 0.44.0. May these changes be published?

**Comment by mockersf** [comment]
👍 https://crates.io/crates/serde_dynamodb/0.5.1

**Comment by Mcat12** [comment]
Thanks for the lightning-fast response! Though, perhaps the changelog should be updated so people know what's changed in this release?

**Comment by mockersf** [comment]
oh right I forgot about this file...
I keep the changelog in GitHub releases : https://github.com/mockersf/serde_dynamodb/releases, I find it easier plus it sends notifications to people interested...
