### ISSUE TITLE
Updated patch version with an updated minor dependency revision

### ISSUE THREAD

**Issue by Luminoth** [mockersf/serde_dynamodb#140]
Hi, it looks like serde_dynamodb did a patch bump while updating a minor revision of the rusoto dependencies. That's a breaking change for anyone that has dependencies like this:

```
rusoto_dynamodb = "0.43"
serde_dynamodb = "0.5"
```

Can serde_dynamodb instead do minor bumps to match minor dependency bumps in order to avoid this?

**Comment by mockersf** [comment]
thanks for reporting this
from now on I'll use the same level of version change as rusoto to avoid issues
