### ISSUE TITLE
Empty string fields do not get serialized

### ISSUE THREAD

**Issue by veedubyou** [mockersf/serde_dynamodb#144]
If I have an object such as
```
struct Foo {
   bar: String,
   other_field: String,
}
```

and if bar is an empty string, then the entire field doesn't get serialized. This might end up being ok if your object hierarchy is fully defined and gets default filled upon deserializing the same payload, but for loosely defined types such as serde::Value, `value != deserialize(serialize(value))`.

**Comment by Hazelfire** [comment]
Bump, this seems to be due to this line:
https://github.com/mockersf/serde_dynamodb/blob/958dd08470d8c8bccc3535999e07277a82e42fcd/serde_dynamodb/src/dynamodb/ser.rs#L114
I'll create a PR addressing this
