### ISSUE TITLE
Support for rusoto_dynamodbstreams::generated::AttributeValue

### ISSUE THREAD

**Issue by eikeon** [mockersf/serde_dynamodb#81]
I've been happily using serde_dynamodb, thank you.

I was hoping to use serde_dynamodb for an AttributeValue coming from a dynamodb stream, too. Or should rusoto_dynamodbstreams use or provide a way to convert to rusoto_dynamodb AttributeValue? Thoughts?

```
serde_dynamodb::from_hashmap(hashmap)?;
                             ^^^^^^^ 
expected struct `rusoto_dynamodb::generated::AttributeValue`, 
found struct `rusoto_dynamodbstreams::generated::AttributeValue`
```

**Comment by mockersf** [comment]
I looked quickly at rusoto_dynamodbstreams, but I never used it. I don't think it will be a change in rusoto, as most of it is generated...

I see two options:
- use features to choose between rusoto_dynamodb or rusoto_dynamodbstreams, but that means both can't be used at the same time
- declare a wrapper trait and implement it for both `AttributeValue`s. I'm not entirely sure it would work, and it means this crate would pull both dependencies even if you don't use both

So... Do you need to use both at the same time ? Or is it either one ?

**Comment by eikeon** [comment]
In my current use case both would be nice. `dynamodbstreams` for the `from_hashmap` and 
 `dynamodb` for the `to_hashmap`. But given a choice of one or the other in this case I'd probably choose `dynamodbstreams` for the `from_hashmap` and deal without the to_hashmap for the other.

**Comment by mockersf** [comment]
I added two features:
- `rusoto_dynamodb`, enabled by default, that adds methods `to_hashmap` and `from_hashmap`
- `rusoto_dynamodbstreams`, disabled by default, that adds methods `to_hashmap_stream` and `from_hashmap_stream`

You should be able to have both features enabled at the same time to work with both DynamoDB and dynamodbstreams.

Could you try with master to check that it works for you ? You can find a little more doc here :
https://mockersf.github.io/serde_dynamodb/serde_dynamodb/index.html#features

If it's good for you I'll push a new version.

**Comment by eikeon** [comment]
Perfect! I should have time to test out master later today and will report back how it goes. Thank you!

**Comment by eikeon** [comment]
I did get a change to start trying it out yesterday, but didn't get a chance to finish as I ran into type `B – Binary` not being implemented. I had not realized that yet as the documentation refers to the list of all dynamodb types.

I was able to from_hashmap_stream a number and a string just fine.

Would it make sense to keep the method names the same and put them in different modules? For example,

```
serde_dynamodb::from_hashmap
serde_dynamodb::to_hashmap
serde_dynamodb::stream::from_hashmap
serde_dynamodb::stream::to_hashmap
```

Or is there more overhead in doing that?

**Comment by mockersf** [comment]
I moved the two methods to the new [`streams`](https://mockersf.github.io/serde_dynamodb/serde_dynamodb/streams/index.html) module

For the missing [`B – Binary`](https://rusoto.github.io/rusoto/rusoto_dynamodb/struct.AttributeValue.html#structfield.b), it's currently not really possible to treat `bytes` as a special case with serde. There is a `serialise_bytes` method that is actually not used as written in their doc: https://serde.rs/impl-serialize.html#other-special-cases.
Either we want to stay in the standard library and use a `&[u8]` or `Vec<u8>` for bytes, or we want to use a crate like [`bytes`](https://docs.rs/bytes/0.4.12/bytes/struct.Bytes.html) (which is used by DynamoDB) but in both case, serde will use the serialisation for slice, vec or struct, and not the one for bytes.
It's the same for all the sets (`BinarySet`, `NumberSet`, `StringSet`) as there is not `Set` in Rust standard library.

**Comment by mockersf** [comment]
version 0.3.0 has been released with this new feature flag
